### ISSUE TITLE
Have a default value for sort_by

### ISSUE THREAD

**Issue by btrd** [fabienpiette/fetcheable_on_api#14]
For example:

`sort_by :created_at, default: :asc`

To sort even if not sort params are given.

**Comment by pauldub** [comment]
How would we deal with the case of multiple sort configurations being defined, for example:

```ruby
sort_by :name
sort_by :created_at
```

I think adding a `#default_sort_by(attributes_and_directions)` would be a better answer.

**Comment by pauldub** [comment]
@btrd is this still an issue?

**Comment by btrd** [comment]
Don't know :/
