### ISSUE TITLE
Add possibility to filter with two parameters

### ISSUE THREAD

**Issue by btrd** [fabienpiette/fetcheable_on_api#4]
Today this works : 
`?filter[first_name]=jean&filter[last_name]=jean`

But it return only records where first_name AND last_name contains `jean`.

And this would be awesome : 
`?filter[name]=jean`

Controller
`filter_by :name, with: -> (collection, value) { collection.where("users.last_name ILIKE ? OR users.first_name ILIKE ?", "%#{value}%", "%#{value}%") }`

**Comment by btrd** [comment]
@pauldub I just edit my issue description

**Comment by pauldub** [comment]
Current behaviour is already to `OR` filters

**Comment by btrd** [comment]
```ruby
Started GET "/v1/users?filter[first_name]=pierre&filter[last_name]=pierre" for 127.0.0.1 at 2018-12-03 16:07:17 +0100
Processing by V1::UsersController#index as */*
  Parameters: {"filter"=>{"first_name"=>"pierre", "last_name"=>"pierre"}, "user"=>{}}
  User Load (12.1ms)  SELECT "users".* FROM "users" WHERE "users"."first_name" ILIKE '%pierre%' AND "users"."last_name" ILIKE '%pierre%'
  ↳ app/controllers/v1/users_controller.rb:15
Completed 200 OK in 49ms (Views: 4.3ms | ActiveRecord: 35.4ms)
```

It's an `AND` operator and not a `OR`

**Comment by btrd** [comment]
?filter[name]=jean

first_name
last_name
